
# Waterways data

# Import data from geojson file
# File from: http://overpass-turbo.eu/

# Query:
# /*
#   This has been generated by the overpass-turbo wizard.
# The original search was:
#   “waterway=*”
# */
#   [out:json][timeout:25];
# // gather results
# (
# // query part for: “waterway=*”
# node["waterway"](59.09702527087121,14.957885742187498,61.17768100166834,19.7369384765625);
# way["waterway"](59.09702527087121,14.957885742187498,61.17768100166834,19.7369384765625);
# relation["waterway"](59.09702527087121,14.957885742187498,61.17768100166834,19.7369384765625);
# );
# // print results
# out body;
# >;
# out skel qt;


# And second query:
# /*
#   This has been generated by the overpass-turbo wizard.
# The original search was:
#   “natural=water”
# */
#   [out:json][timeout:25];
# // gather results
# (
# // query part for: “natural=water”
# node["natural"="water"](59.09702527087121,14.957885742187498,61.17768100166834,19.7369384765625);
# way["natural"="water"](59.09702527087121,14.957885742187498,61.17768100166834,19.7369384765625);
# relation["natural"="water"](59.09702527087121,14.957885742187498,61.17768100166834,19.7369384765625);
# );
# // print results
# out body;
# >;
# out skel qt;

# Based on tips from:
# https://github.com/Robinlovelace/Creating-maps-in-R/blob/master/vignettes/geoJSON.Rmd

library(rgdal)
library(jsonlite)

# Do we have GeoJSON support?
"GeoJSON" %in% ogrDrivers()$name



water.points <- readOGR("export.geojson", "OGRGeoJSON", require_geomType="wkbPoint")
# str(water.points)

water.lines <- readOGR("export.geojson", "OGRGeoJSON", require_geomType="wkbLineString")

water.polygons <- readOGR("export.geojson", "OGRGeoJSON", require_geomType="wkbPolygon")


# Second set of data
water.points2 <- readOGR("all_natural_water.geojson", "OGRGeoJSON", require_geomType="wkbPoint")
# str(water.points)

water.lines2 <- readOGR("all_natural_water.geojson", "OGRGeoJSON", require_geomType="wkbLineString")

water.polygons2 <- readOGR("all_natural_water.geojson", "OGRGeoJSON", require_geomType="wkbPolygon")

# # ?save
# save(list=(c("water.points", "water.lines", "water.polygons")),
#      file = "waterways.Rdata")
# 
# # Load same data
# load("waterways.Rdata")
# 
# # See how the data look:
# plot(lines, col="#7f7f7f")
# plot(polygons, add=TRUE, col = "blue")

# ?save
save(list=(c("water.points", "water.lines", "water.polygons",
             "water.points2", "water.lines2", "water.polygons2")),
     file = "waterways.Rdata")

# Load same data
load("waterways.Rdata")

# See how the data look:
plot(water.lines2, col="red", add = TRUE)
plot(water.polygons2, add=TRUE, col = "red")
# plot(water.points, add=TRUE, col="red")


water.polygons2.sub <- water.polygons2[water.polygons2@data$water %in% c("lake", "pond", "river", "reservoir"),]
summary(water.polygons2@data$water %in% c("lake", "pond", "river", "reservoir"))

# 
# summary(water.polygons2@data$)
#         %in% c("lake", "pond", "river", "reservoir"))


plot(water.polygons2, add=TRUE, col = "blue", border=NA)
plot(water.polygons, add=TRUE, col = "blue", border = NA)

plot(water.lines2, add=TRUE, col = "red", lwd = 0.5, border=NA)
plot(water.lines, add=TRUE, col = "red", lwd = 0.5, border = NA)

summary(water.polygons2@data)



# Use this answer for working out which points lie in polygons:
# http://gis.stackexchange.com/questions/131168/buffer-and-union-in-r-without-reducing-to-a-multi-polygon
